openapi: "3.0.3"
info:
  title: "com_the_chance_honey_mart API"
  description: "com_the_chance_honey_mart API"
  version: "1.0.0"
servers:
- url: "https://com_the_chance_honey_mart"

tags:
  - name: Categories
    description: Operations about categories
  - name: Markets
    description: Operations about markets
  - name: Products
    description: Operations about products

paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /category:
    post:
      tags:
        - Categories
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "marketId"
        in: "query"
        required: false
        schema:
          type: "number"
      - name: "imageId"
        in: "query"
        required: false
        schema:
          type: "integer"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Category"
    put:
      tags:
        - Categories
      description: ""
      parameters:
      - name: "id"
        in: "query"
        required: false
        schema:
          type: "number"
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
  /category/{id}:
    delete:
      tags:
        - Categories
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
  /category/{categoryId}:
    get:
      tags:
        - Categories
      description: "get all products in category"
      parameters:
      - name: "categoryId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryWithProduct"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
  /deleteAllTables:
    delete:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
  /markets:
    get:
      tags:
        - Markets
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Market"
    post:
      tags:
        - Markets
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Market"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
  /markets/{id}:
    delete:
      tags:
        - Markets
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
    put:
      tags:
        - Markets
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "number"
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Market"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
  /markets/{id}/categories:
    get:
      tags:
        - Markets
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "number"
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Category"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
  /marketsWithCategories:
    get:
      tags:
        - Markets
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MarketWithCategories"
  /product:
    post:
      tags:
        - Products
      description: ""
      parameters:
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "price"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "quantity"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "categoriesId"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductWithCategory"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
  /product/{id}:
    delete:
      tags:
        - Products
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "boolean"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
    put:
      tags:
        - Products
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "name"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "price"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "quantity"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "boolean"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
  /product/{productId}:
    get:
      tags:
        - Products
      description: ""
      parameters:
      - name: "productId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Category"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
  /product/{id}/updateCategories:
    put:
      tags:
        - Products
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      - name: "categoriesId"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductWithCategory"
        "406":
          description: "Not Acceptable"
          content:
            '*/*':
              schema:
                type: "string"
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
  /products:
    get:
      tags:
        - Products
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Product"
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    Category:
      type: "object"
      properties:
        categoryId:
          type: "integer"
          format: "int64"
        categoryName:
          type: "string"
        imageId:
          type: "integer"
          format: "int32"
    Product:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        quantity:
          type: "string"
        price:
          type: "number"
          format: "double"
    CategoryWithProduct:
      type: "object"
      properties:
        categoryId:
          type: "integer"
          format: "int64"
        categoryName:
          type: "string"
        categoryImageId:
          type: "integer"
          format: "int32"
        products:
          type: "array"
          items:
            $ref: "#/components/schemas/Product"
    Market:
      type: "object"
      properties:
        marketId:
          type: "integer"
          format: "int64"
        marketName:
          type: "string"
    MarketWithCategories:
      type: "object"
      properties:
        marketId:
          type: "integer"
          format: "int64"
        marketName:
          type: "string"
        categories:
          type: "array"
          items:
            $ref: "#/components/schemas/Category"
    ProductWithCategory:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        quantity:
          type: "string"
        price:
          type: "number"
          format: "double"
        category:
          type: "array"
          items:
            $ref: "#/components/schemas/Category"